---
- name: Gather facts
  ansible.builtin.setup:
    gather_subset:
      - min
      - distribution
      - distribution_version

- name: Decide Tomcat package/service by Ubuntu version
  ansible.builtin.set_fact:
    tomcat_pkg: >-
      {{ 'tomcat10' if (ansible_facts.distribution == 'Ubuntu'
                        and ansible_facts.distribution_version is version('24.04', '>=')) else 'tomcat9' }}
    tomcat_service: "{{ tomcat_pkg }}"

- name: Derive server_xml_path if unset
  ansible.builtin.set_fact:
    _server_xml_path: "/etc/{{ tomcat_pkg }}/server.xml"
  when: (server_xml_path | default('')) | length == 0
  
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: ansible_facts.os_family == 'Debian'

- name: Install Java
  ansible.builtin.apt:
    name: "{{ tomcat_java_package }}"
    state: present

- name: Install Tomcat
  ansible.builtin.apt:
    name: "{{ tomcat_pkg }}"
    state: present

- name: Render /etc/default/{{ tomcat_pkg }}
  ansible.builtin.template:
    src: default-tomcat.j2
    dest: "/etc/default/{{ tomcat_pkg }}"
    owner: root
    group: root
    mode: "0644"
  when: manage_tomcat_default
  notify: restart tomcat

- name: Manage server.xml (optional)
  ansible.builtin.blockinfile:
    path: "{{ server_xml_path }}"
    create: false
    marker: "<!-- {mark} ANSIBLE MANAGED TOMCAT CONNECTOR BLOCK -->"
    block: |
      <!-- HTTP/1.1 Connector -->
      <Connector port="{{ tomcat_port }}"
                 protocol="org.apache.coyote.http11.Http11NioProtocol"
                 address="{{ tomcat_bind_address }}"
                 redirectPort="8443" />
      <!-- Optional AJP -->
      <!-- <Connector protocol="AJP/1.3" address="{{ tomcat_bind_address }}" port="{{ tomcat_ajp_port }}" redirectPort="8443" /> -->
  when: manage_server_xml
  notify: restart tomcat

- name: Ensure Tomcat is enabled and running
  ansible.builtin.service:
    name: "{{ tomcat_service }}"
    state: started
    enabled: true


# --- Optional WAR deployment ---
- name: Deploy WAR if enabled
  ansible.builtin.include_tasks: deploy_war.yml
  when: tomcat_deploy_enabled
